version: '3.1'

services:
  php:
    image: 'hexagonal-workshop/dev/php:7.4'
    environment:
      APP_ENV: '${APP_ENV:-prod}'
      COMPOSER_HOME: '/var/www/.composer'
      PHP_IDE_CONFIG: 'serverName=hexagonal-workshop-cli'
      XDEBUG_ENABLED: '${XDEBUG_ENABLED:-0}'
      XDEBUG_CONFIG: 'remote_host=${REMOTE_HOST:-172.17.0.1}'
      BLACKFIRE_CLIENT_ID: '${BLACKFIRE_CLIENT_ID:-client_id}'
      BLACKFIRE_CLIENT_TOKEN: '${BLACKFIRE_CLIENT_TOKEN:-client_token}'
    volumes:
      - './.git:/srv/.git'
      - '.:/srv/hexagonal-workshop'
      - '${HOST_COMPOSER_HOME:-~/.composer}:/var/www/.composer'
    working_dir: '/srv/hexagonal-workshop'
    command: 'php'
    networks:
      - 'hexagonal-workshop'

  fpm:
    image: 'hexagonal-workshop/dev/php:7.4'
    environment:
      APP_ENV: '${APP_ENV:-prod}'
      PHP_IDE_CONFIG: 'serverName=hexagonal-workshop'
      XDEBUG_ENABLED: '${XDEBUG_ENABLED:-0}'
      XDEBUG_CONFIG: 'remote_host=${REMOTE_HOST:-172.17.0.1}'
      BLACKFIRE_CLIENT_ID: '${BLACKFIRE_CLIENT_ID:-client_id}'
      BLACKFIRE_CLIENT_TOKEN: '${BLACKFIRE_CLIENT_TOKEN:-client_token}'
    volumes:
      - '.:/srv/hexagonal-workshop:rw'
    working_dir: '/srv/hexagonal-workshop'
    command: 'php-fpm -F'
    networks:
      - 'hexagonal-workshop'

  httpd-back:
    image: 'httpd:2.4'
    environment:
      APP_ENV: '${APP_ENV:-prod}'
    depends_on:
      - 'fpm'
    ports:
      - '${DOCKER_PORT_HTTP:-8002}:80'
    volumes:
      - '.:/srv/hexagonal-workshop:ro'
      - './infra/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro'
      - './infra/httpd/back.conf:/usr/local/apache2/conf/vhost.conf:ro'
    networks:
      - 'hexagonal-workshop'

  db:
    image: 'postgres:12.1'
    ports:
      - '${DOCKER_PORT_POSTGRES:-5434}:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=book_store
      - POSTGRES_DB=book_store_test
    networks:
      - 'hexagonal-workshop'

  blackfire:
    image: blackfire/blackfire
    environment:
      BLACKFIRE_SERVER_ID: '${BLACKFIRE_SERVER_ID:-server_id}'
      BLACKFIRE_SERVER_TOKEN: '${BLACKFIRE_SERVER_TOKEN:-server_token}'
    networks:
      - 'hexagonal-workshop'

networks:
  hexagonal-workshop:
